biheybazar/biheybazar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from . import views
from users import views as user_views

# Routing is defined here
urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)), # To use django debugger
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^vendors/', include('vendors.urls', namespace="vendors")),
    url(r'^checklist/', include('checklist.urls', namespace="checklist")),
    # path('verification/', include('verify_email.urls')),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     user_views.activate, name='activate'),
    path('activate/<uidb64>/<token>', user_views.activate, name="activate")
] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT) # To include media urls

biheybazar/checklist/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import re_path, path
from users import views as user_views

app_name = "checklist"

urlpatterns = [
    url(r'^$', user_views.checklist_url, name="all"),
    url(r'^create/$', views.CreateChecklist.as_view(), name="checklist_create"),
    re_path(r'^(?P<pk>[-\w]+)/$', views.ChecklistDetail.as_view(), name="checklist_detail"),
    url(r'^delete/note/(?P<pk>[-\w]+)/$', views.DeleteNote.as_view(), name="note_delete"),
    url(r'^delete/category/(?P<pk>[-\w]+)/$', views.DeleteChecklistCategory.as_view(), name="checklistcategory_delete"),
    url(r'^remove/vendor/(?P<pk>[-\w]+)/$', views.RemoveChecklistVendor.as_view(), name="vendor_remove"),
    url(r'^delete/checklist/(?P<pk>[-\w]+)/$', views.DeleteChecklist.as_view(), name="checklist_delete"),
    url(r'^remove/collaborator/(?P<pk>[-\w]+)/$', views.removeCollaborator, name='collaborator_remove'),
]

biheybazar/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'check/',views.userCheckView,name='check'),
    url(r'^signup/customer/$', views.customerSignUpView, name="signup_customer"),
    url(r'^signup/vendor/$', views.vendorSignUpView, name="signup_vendor"),
]

biheybazar/vendors/urls.py
from django.conf.urls import url
from . import views
from reviews import views as re_view

app_name = "vendors"
urlpatterns = [
    url(r'^new/tag/$', views.CreateTag.as_view(), name="create_tag"),
    # url(r'^add/tag/$', views.AddTag.as_view(), name="add_tag"),
    # url(r'^remove/tag/$', views.RemoveTag.as_view(), name="remove_tag"),
    url(r'^new/category/$', views.CreateCategory.as_view(), name="create_category"),
    url(r'^profile/(?P<slug>[-\w]+)/$', views.VendorProfile.as_view(), name='profile'),
    url(r'^delete/image/(?P<pk>[-\w]+)/$', views.DeleteVendorImage.as_view(), name="image_delete"),
    url(r'^delete/pricing/(?P<pk>[-\w]+)/$', views.DeleteVendorPricing.as_view(), name="pricing_delete"),
    url(r'list/', views.VendorListView.as_view(), name="vendor_list"),
    url(r'venues/',views.VenueListView.as_view(),name='venues'),
    url(r'^category/(?P<pk>[-\w]+)/$',views.CategoryDetailView.as_view(),name='vendorCategory'),
    url(r'^recommendations/$', views.RecommendationListView.as_view(), name="recommendation_list"),
]

biheybazar/checklist/models.py
from django.db import models
from customers.models import Customer
from vendors.models import Vendor
from django.urls import reverse

# Create your models here.
class Checklist(models.Model):
    checklist_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    author = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="author")
    can_edit = models.BooleanField(default=True)
    collaborators = models.ManyToManyField(Customer, blank=True)

    def __str__(self):
        return self.checklist_name
    
    def get_absolute_url(self):
        return reverse('checklist:checklist_detail', kwargs={'pk': self.pk})

class ChecklistCategory(models.Model):
    cat_name = models.CharField(max_length=100)
    checklist = models.ForeignKey(Checklist, on_delete=models.CASCADE, related_name="checklist")
    vendors = models.ManyToManyField(Vendor, through='VendorChecklistCategory', blank=True)

    def __str__(self):
        return self.cat_name

class Note(models.Model):
    text = models.CharField(max_length=300)
    category = models.ForeignKey(ChecklistCategory, on_delete=models.CASCADE, related_name="category_note")

    def __str__(self):
        return self.text

# class Collaborators(models.Model):
#     checklist = models.ForeignKey(Checklist, on_delete=models.CASCADE)
#     collaborator = models.ForeignKey(Customer, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.checklist.checklist_name

class VendorChecklistCategory(models.Model):
    category = models.ForeignKey(ChecklistCategory, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.comment

biheybazar/checklist/forms.py
from django.db.models.base import Model
from django.forms import ModelForm, Form, CharField
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404
from .models import Checklist, ChecklistCategory, Note
from customers.models import Customer

class CreateChecklistForm(ModelForm):
    class Meta:
        exclude=('author', "can_edit", "collaborators")
        model = Checklist

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.customer_object = Customer.objects.filter(user=user).first()

    def save(self):
        checklist = Checklist.objects.create(
            checklist_name=self.cleaned_data['checklist_name'], # foreign key -> user object
            description=self.cleaned_data['description'],
            author=self.customer_object,
            can_edit=True)
        print(self.customer_object.user.pk)
        print(checklist.pk)
        return checklist

    
class CreateChecklistCategoryForm(ModelForm):
    class Meta:
        fields = ("cat_name",)
        model = ChecklistCategory

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat_name'].label = "Category Name"

    def save(self, checklist):
        checklist_category = ChecklistCategory.objects.create(
            cat_name=self.cleaned_data['cat_name'],
            checklist = checklist
        )
        return checklist_category

class CreateNoteForm(ModelForm):
    class Meta:
        fields = ("text",)
        model = Note

    # def __init__(self, *args, **kwargs):
    #     category = kwargs.pop('template_category')
    #     print(category)
    #     super().__init__(*args, **kwargs)
    #     self.category = get_object_or_404(ChecklistCategory, pk=category)
    
    def save(self, category):
        note = Note.objects.create(
            text=self.cleaned_data['text'],
            category = category
        )
        return note

class AddCollaborator(Form):

    collaborators = CharField(label="Username", max_length=200)


    # class Meta:

        # fields = ("collaborators",)
        # model = Checklist
        # widgets = {
        #     'collaborators': CharField,
        # }

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['collaborators'].label = "Username"

    def save(self, collaborator, checklist):
        checklist = Checklist.objects.filter(pk=checklist).first()
        print('Collaborators', collaborator)
        print('Checklist: ', checklist)
        checklist.collaborators.add(collaborator)
        return checklist

biheybazar/checklist/views.py
from django.contrib.auth import login
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect, request, response
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls.base import reverse_lazy
from django.views.generic.edit import FormMixin
from django.views.generic import (CreateView, DetailView, DeleteView, View,
                                    UpdateView, ListView, RedirectView, FormView)
from django.contrib import messages

from .forms import CreateChecklistForm, CreateChecklistCategoryForm, CreateNoteForm, AddCollaborator
from .models import Checklist, ChecklistCategory, Note, VendorChecklistCategory
from customers.models import Customer

# Create your views here.

class CreateChecklist(LoginRequiredMixin, CreateView):
    form_class = CreateChecklistForm
    template_name = "checklist/create_checklist.html"
    model = Checklist
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    

class DeleteNote(LoginRequiredMixin, DeleteView):
    model = Note

    def get_success_url(self):
        return reverse_lazy('checklist:checklist_detail', kwargs={'pk':self.request.session.get('checklist_pk')})

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class DeleteChecklistCategory(LoginRequiredMixin, DeleteView):
    model = ChecklistCategory

    def get_success_url(self):
        return reverse_lazy('checklist:checklist_detail', kwargs={'pk':self.request.session.get('checklist_pk')})

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class RemoveChecklistVendor(LoginRequiredMixin, DeleteView):
    model = VendorChecklistCategory

    def get_success_url(self):
        return reverse_lazy('checklist:checklist_detail', kwargs={'pk':self.request.session.get('checklist_pk')})

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class DeleteChecklist(LoginRequiredMixin, DeleteView):
    model = Checklist
    template_name = 'checklist/checklist_confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('checklist:all')

@login_required
def removeCollaborator(request, pk):
    checklist = Checklist.objects.filter(pk=pk).first()
    customer = Customer.objects.filter(user=request.user).first()
    checklist.collaborators.remove(customer)
    return HttpResponseRedirect(reverse_lazy("checklist:all"))

class ChecklistDetail(LoginRequiredMixin, DetailView, FormView):
    model = Checklist
    template_name = "checklist/checklist_detail.html"
    form_class = CreateChecklistForm
    # fourth_form_class = CreateChecklistCategoryForm
    # second_form_class = CreateNoteForm
    # third_form_class = AddCollaborator
    def get_context_data(self, **kwargs):
        self.request.session['checklist_pk'] = self.kwargs['pk']
        customers = Customer.objects.filter(user__username=self.request.user.username)
        author_checklist = Checklist.objects.filter(author__in=customers)
        checklists = Checklist.objects.all()
        checklist = Checklist.objects.get(pk=self.kwargs['pk'])
        customer_obj = Customer.objects.get(user__username=self.request.user.username)
        category_vendors = VendorChecklistCategory.objects.filter(category__checklist=checklist)
        # print(Customer.objects.filter(user__username=self.request.user.username))
        # categories = get_list_or_404(ChecklistCategory, checklist=checklist)
        categories = ChecklistCategory.objects.filter(checklist=checklist)  
        context = super(ChecklistDetail, self).get_context_data(**kwargs)
        context['category_vendors'] = category_vendors
        context['checklists'] = checklists
        context['checklist'] = checklist
        context['author_checklist'] = author_checklist
        context['checklist_category'] = categories
        context['notes'] = Note.objects.all()
        context['customer_obj'] = customer_obj
        # if 'form' not in kwargs:
        #     kwargs['form'] = CreateChecklistForm()
        if 'checklistcategory_form' not in context:
            context['checklistcategory_form'] = CreateChecklistCategoryForm()
        if 'note_form' not in context:
            context['note_form'] = CreateNoteForm()
        if 'collaborator_form' not in context:
            context['collaborator_form'] = AddCollaborator()
            # print(context['checklistcategory_form'])
        return context
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs()  
        kwargs['user'] = self.request.user
        return kwargs

    # def form_valid(self, form):
    #     if 'form' in self.request.POST:
    #         form.save(self.checklist)
    #     else:
    #         print(form.cleaned_data['text'])
    #         form.save(self.category)
    #     return HttpResponseRedirect(self.request.path_info)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = {}

        # if 'form' in request.POST:
        #     checklist_form = CreateChecklistForm(request.POST)
        #     if checklist_form.is_valid():
        #         context['form'] = checklist_form
        #     else:
        #         context['form'] = checklist_form

        if 'checklist_category' in request.POST:
            checklistcategory_form = CreateChecklistCategoryForm(request.POST)
            
            if checklistcategory_form.is_valid():
                checklistcategory_form.save(Checklist.objects.filter(pk=self.kwargs['pk']).first())
            else:
                context['checklistcategory_form'] = checklistcategory_form
        
        elif 'note' in request.POST:
            note_form = CreateNoteForm(request.POST)

            if note_form.is_valid():
                category = ChecklistCategory.objects.filter(pk=self.request.POST.get('category_pk')).first()
                note_form.save(category)
            else:
                context['note_form'] = note_form
        
        elif 'collaborator' in request.POST:
            collaborator_form = AddCollaborator(request.POST)

            if collaborator_form.is_valid():
                try:
                    collaborator = Customer.objects.filter(user__username=collaborator_form.cleaned_data['collaborators']).first()
                except:
                    messages.error(self.request, 'Invalid Username!')
                else:
                    checklist = self.kwargs['pk']
                    collaborator_form.save(collaborator, checklist)
            else:
                context['collaborator_form'] = collaborator_form
        
        return render(request, self.template_name, self.get_context_data(**context))


# class CreateCategory(LoginRequiredMixin, CreateView):
#     model = ChecklistCategory
#     form_class = CreateChecklistCategoryForm
#     template_name = "checklist/checklist_detail.html"

#     def get_form_kwargs(self, **kwargs):
#         kwargs = super().get_form_kwargs()
#         kwargs['checklist'] = self.kwargs['pk']
#         return kwargsn 

    # def get_context_data(self, **kwargs):
    #     category_form =  self.form_class
    #     context = super(CreateCategory, self).get_context_data(**kwargs)
    #     context['category_form'] = category_form
    #     return context

biheybazar/checklist/templates/checklist/checklist_confirm_delete.html
{% extends 'users/base.html' %}


{% block content %}
<div class="container">
    <center>
        <div style="margin-top: 10%;">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete the checklist, "{{ object }}"?</p>
                <input type="submit" class="btn btn-danger" value="Confirm">
            </form>
        </div>
        
    </center>
    
</div>

{% endblock content %}
    

biheybazar/checklist/templates/checklist/checklist_detail.html
{% extends 'users/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/checklist.css' %}">

<div class="container-fluid">
    <div class="col-lg-3 col-sm-12 m-auto">

        {% include 'checklist/messages.html' %}

    </div>
</div>

<!-- Main Code -->
<input type="checkbox" id="check" checked>
<!-- Sidebar -->
<div class="sidebar">
    <div class="mychecklist">
        <h4><i class="fas fa-clipboard-list"></i> My Checklist
            <label for="check">
                <span><i class="fas fa-bars" id="sidebar-toggle-1"></i></span>
            </label>
        </h4>
        <ul>
            {% for list in author_checklist %}
            <li><a href="{% url 'checklist:checklist_detail' pk=list.pk %}">{{list.checklist_name}}</a></li>
            {% endfor %}
        </ul>
        {% if user.is_customer %}
        <center>
            <a href="{% url 'checklist:checklist_create' %}"><i class="fas fa-plus" id="add-checklist"></i></a>
        </center>
        {% endif %}
    </div>
    <div>
        <hr class="my-4">
    </div>
    <div class="sharedchecklist">
        <h4> <span><i class="fas fa-share-alt-square"></i></span> Shared Checklist</h4>
        <ul>
            {% for list in checklists %}
            {% if customer_obj in list.collaborators.all %}
            <li><a href="{% url 'checklist:checklist_detail' pk=list.pk %}">{{list.checklist_name}}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
<!-- Checklist -->
{% if checklist.author == customer_obj or customer_obj in checklist.collaborators.all %}
<div class="checklist">
    <div class="checklist-header">
        <div class="checklist-details">
            <label for="check">
                <span><i class="fas fa-bars" id="sidebar-toggle"></i></span>
            </label>
            <h3>{{ checklist.checklist_name }}</h3><br>
            <p class="lead">{{ checklist.description }}
                {% if checklist.author == customer_obj %}
                <a class="icon" data-toggle="modal" data-target="#staticBackdrop">
                    <span class="material-icons checklist-share">share</span>
                </a><span class="popup">Share Checklist</span></h6>
                <!-- Modal -->
            <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
                aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Invite Collaborators</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{% url 'checklist:checklist_detail' pk=checklist.pk %}">
                                {% csrf_token %}
                                {% bootstrap_form collaborator_form %}
                                <input type="submit" class="btn btn-primary" value="Add To Checklist"
                                    name="collaborator">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <div>
        <hr class="my-4">
    </div>
    <div class="container categories">
        <h2>Categories
            <a class="icon" id="category-button-show">
                <span class="material-icons category-add">add_box</span>
            </a><span class="popup">Add Category</span>
        </h2>
        <div class="card-form mb-4" id="category-form">
            <form method="POST" action="{% url 'checklist:checklist_detail' pk=checklist.pk %}">
                {% csrf_token %}
                {% bootstrap_form checklistcategory_form %}
                <input type="submit" class="btn btn-primary" name="checklist_category" value="Create Category">
                <a class="icon" id="category-button-hide">
                    <span class="material-icons delete">clear</span>
                </a><span class="popup">Close Form</span>
            </form>

        </div>
        <div>
            <hr class="my-2 mb-4 mt-3">
        </div>
        
            <!-- Vendor Categories -->
            {% for category in checklist_category %}
            <div class="vendor-category">
                <div class="container category-info">
                    <h4 class="category-name">{{category.cat_name}}
                        <div>
                            <a href="{% url 'checklist:checklistcategory_delete' pk=category.pk %}" class="icon"><span class="material-icons category-delete">delete</span></a><span
                                class="popup">Delete Category</span>
                            <a class="icon1 note-button-show" id="note-button-show-{{category.pk}}" value="{{category.pk}}"><span class="material-icons note-add">post_add</span></a><span
                                class="popup1">Add Note</span>
                        </div>
                    </h4>
                    <div class="card-form mb-4 note-form" id="note-form-{{category.pk}}">
                        <form method="POST" action="{% url 'checklist:checklist_detail' pk=checklist.pk %}">
                            {% csrf_token %}
                            {% bootstrap_form note_form %}
                            <input type="hidden" name="category_pk" value='{{category.pk}}'>
                            <input type="submit" class="btn btn-primary" name="note" value="Add Note">
                            <a class="icon note-button-hide" id="category-button-hide-{{category.pk}}" value="{{category.pk}}">
                                <span class="material-icons delete">clear</span>
                            </a><span class="popup">Close Form</span>
                        </form>
                        
                    </div>
                    {% for note in notes %}
                    {% if note.category == category %}
                    <div class="category-note mb-4">
                        <p>{{note.text}}
                            <a href="{% url 'checklist:note_delete' pk=note.pk %}" class="icon">
                                <span class="material-icons delete">remove_circle_outline</span>
                            </a><span class="popup">Delete Note</span>
                        </p>
                    </div>
                </h4>
                <div class="card-form mb-4 note-form" id="note-form-{{category.pk}}">
                    <form method="POST" action="{% url 'checklist:checklist_detail' pk=checklist.pk %}">
                        {% csrf_token %}
                        {% bootstrap_form note_form %}
                        <input type="hidden" name="category_pk" value='{{category.pk}}'>
                        <input type="submit" class="btn btn-primary" name="note" value="Add Note">
                        <a class="icon note-button-hide" id="category-button-hide-{{category.pk}}"
                            value="{{category.pk}}">
                            <span class="material-icons delete">clear</span>
                        </a><span class="popup">Close Form</span>
                    </form>
                    {% endif %}
                    {% endfor %}
                </div>
                {% for vendor in category_vendors %}
                {% if vendor.category == category %}
                <div class="vendor-card mb-4">
                    <div class="vendor-image">
                        <img src="{{vendor.vendor.logo.url}}" alt="">
                    </div>
                    <div class="vendor-info">
                        <h5 class="vendor-name"><a href="{% url 'vendors:profile' slug=vendor.vendor.user.username %}">{{vendor.vendor.vendor_name}}</a>
                            <a href="{% url 'checklist:vendor_remove' pk=vendor.pk %}" class="icon">
                                <span class="material-icons delete">clear</span>
                            </a><span class="popup">Remove Vendor</span>
                        </h5>
                        <p class="vendor-comment">{{vendor.comment}}</p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            
            {% endfor %}
        </div>
        <div>
            <hr class="my-2 mb-4">

        </div>
        <div>
            <div class="checklist-footer">
                <div class="checklist-footer-details">
                    <p>Checklist Owner : <i>{{ checklist.author }}</i></p><br>
                    <p>Checklist Holders :                       
                            
                        {% for i in checklist.collaborators.all %}                              
                            <i>{{i}}</i>
                        {% empty %}
                            <i>No collaborators yet</i> 
                        {% endfor %}
                        
                        {% if checklist.author == customer_obj %}
                            <a href="{% url 'checklist:checklist_delete' pk=checklist.pk %}" class="icon">
                                <span class="material-icons checklist-delete">delete</span>
                            </a>
                            <span class="popup">Delete Checklist</span>
                        {% endif %}
                        
                        {% if customer_obj in checklist.collaborators.all %}
                            <a href="{% url 'checklist:collaborator_remove' pk=checklist.pk %}" class="icon">
                                <span class="material-icons checklist-delete">delete</span>
                            </a>
                            <span class="popup">Remove Checklist</span>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}
</main>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#category-form").hide();

        $("#collab-form").hide();

        $(".note-form").hide();

        $("#category-button-show").click(function () {
            $("#category-form").show();
        });
        $("#category-button-hide").click(function () {
            $("#category-form").hide();
        });
        $("#collab-button-show").click(function () {
            $("#collab-form").show();
        });
        $("#collab-button-hide").click(function () {
            $("#collab-form").hide();
        });
        $(".note-button-show").click(function () {
            var value = $(this).attr("value");
            $("#note-form-" + value).show();
        })
        $(".note-button-hide").click(function () {
            var value = $(this).attr("value");
            $("#note-form-" + value).hide();

        })
    });

</script>
{% endblock content %}

biheybazar/checklist/templates/checklist/create_checklist.html
{% extends 'users/base.html' %}

{% load bootstrap4 %}


{% block title %}
    BiheyBazar- Create Checklist
{% endblock title %}
    

{% block content %}
    
    {% if user.is_customer %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="Create Checklist">
        </form>
    </div>
    {% endif %}
    
{% endblock content %}
    

biheybazar/checklist/templates/checklist/create_checklist_category.html
{% load bootstrap4 %}

<div>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>

biheybazar/checklist/templates/checklist/messages.html
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            
        </div>
    {% endfor %}