biheybazar/biheybazar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from . import views
from users import views as user_views

# Routing is defined here
urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)), # To use django debugger
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^vendors/', include('vendors.urls', namespace="vendors")),
    url(r'^checklist/', include('checklist.urls', namespace="checklist")),
    # path('verification/', include('verify_email.urls')),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     user_views.activate, name='activate'),
    path('activate/<uidb64>/<token>', user_views.activate, name="activate")
] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT) # To include media urls

biheybazar/customers/urls.py
from django.conf.urls import url
from . import views

app_name = "customers"
urlpatterns = [
    url(r'^questions/$', views.Questions.as_view(),name='questions'),
    url(r'^profile/(?P<pk>[-\w]+)/$', views.CustomerProfile.as_view(), name='profile')
]

biheybazar/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'check/',views.userCheckView,name='check'),
    url(r'^signup/customer/$', views.customerSignUpView, name="signup_customer"),
    url(r'^signup/vendor/$', views.vendorSignUpView, name="signup_vendor"),
]

biheybazar/customers/models.py
from django.db import models
from users.models import User

# Create your models here.
class Customer(models.Model):

    # ENUM field for location choices (user can choose between one of them)
    LOCATION_CHOICES = (
        (1, "Kathmandu"),
        (2, "Pokhara"),
        (3, "Chitwan"),
        (4, "Janakpur"),
        (5, "Dang")
    )
    # ENUM field for culture choices (user can choose between one of them)
    CULTURE_CHOICES = (
        (1, 'Brahmin'),
        (2, 'Newar'),
        (3, 'Tharu'),
        (4, 'Terai')
    )

    # A One-to-one Relationship between user and customer.
    # Allows addition of fields which are only specific to Customers
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    location = models.PositiveIntegerField(choices=LOCATION_CHOICES, blank=True, null=True)
    culture = models.PositiveIntegerField(choices=CULTURE_CHOICES, blank=True, null=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='profile_pic',default='user.png')

    def __str__(self):
        return self.user.username

biheybazar/customers/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm, PasswordInput, CharField, Form
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.hashers import check_password
from customers.models import Customer
from users.models import User





class RecommendationForm(ModelForm):
    '''recommendation forms contains two fields, location and culture'''

    class Meta:
        model= Customer
        fields=('location','culture')

    # def __init__(self, *args, **kwargs):
    #     self.customer = kwargs.pop('customer')
    #     super().__init__(*args, **kwargs)
    
    # def save(self):
    #     print(self.customer)
    #     self.customer.location = self.cleaned_data['location']
    #     self.customer.culture=self.cleaned_data['culture']
    #     # form = super(RecommendationForm, self).save()
    #     # print(form)
    #     return self.customer

class ChangeProfilePicForm(ModelForm):
    class Meta:
        model = Customer
        fields = ('profile_pic',)

    def save(self, customer):
        customer.profile_pic = self.cleaned_data['profile_pic']
        customer.save()

class ChangePasswordForm(Form):
    old_password = CharField(widget=PasswordInput)
    new_password = CharField(widget=PasswordInput, validators=[validate_password])
    confirm_password = CharField(widget=PasswordInput)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        confirm_password = cleaned_data.get('confirm_password')
        new_password = cleaned_data.get('new_password')
    
        if new_password != confirm_password:
            self.add_error('confirm_password', 'Password does not match.')

    def save(self, user):
        if user.check_password(self.cleaned_data['old_password']):
            user.set_password(self.cleaned_data['new_password'])
            user.save()

biheybazar/customers/views.py
from django.shortcuts import render
from django.views.generic import (UpdateView, FormView, DetailView)
from .models import Customer
from .forms import RecommendationForm, ChangeProfilePicForm, ChangePasswordForm
from users.forms import CustomerSignUpForm
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class Questions(LoginRequiredMixin,FormView):
    '''CBV to ask questions to customer and store the answers in location and culture field of Customer model '''
    model = Customer
    template_name='customers/questions.html'
    # login_url ='/login/'
    form_class = RecommendationForm
    success_url='/'


    #check the validation of Recommendation form
    def form_valid(self,form):
        customer=Customer.objects.filter(user=self.request.user).first()
        recommend_form=form.save(commit=False)
        form.instance.location=form.cleaned_data['location']
        form.instance.culture=form.cleaned_data['culture']
        if recommend_form.user_id is None:
            recommend_form.user_id=self.request.user.id

        form.save()

        return super().form_valid(form)

    # def post(self,request,*args,**kwargs):
    #     # self.object = self.get_object()
    #     customer=Customer.objects.filter(user=self.request.user).first()
    #     context={}
    #     if 'form' in request.POST:
    #         recommend_form=RecommendationForm(request.POST)
    #         print(recommend_form.cleaned_data['location','culture'])
    #         if recommend_form.is_valid():

    #             recommendations=recommend_form.save(commit=False)
    #             recommendations.location=recommend_form.cleaned_data['location']
    #             recommendations.culture=recommend_form.cleaned_data['culture']
    #             recommendations.save()

    #         else:
    #             context['form']=recommend_form

    #     return render(request,self.template_name,self.get_context_data(**context))

    # def get_form_kwargs(self, **kwargs):
    #     kwargs = super().get_form_kwargs()
    #     # print( Customer.objects.filter(user=self.request.user).first())
    #     kwargs['customer'] = Customer.objects.filter(user=self.request.user).first()
    #     return kwargs


class CustomerProfile(FormView, DetailView):
    model = Customer
    form_class = CustomerSignUpForm
    template_name = "customers/customers_profile.html"
    def get_context_data(self, **kwargs):
        customer = Customer.objects.filter(user__pk=self.kwargs['pk']).first()
        context = super(CustomerProfile, self).get_context_data(**kwargs)
        context['customer'] = customer
        if 'change_profile_pic_form' not in context:
            context['change_profile_pic_form'] = ChangeProfilePicForm()
        if 'change_password_form' not in context:
            context['change_password_form'] = ChangePasswordForm()
        return context

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        context = {}
        customer = Customer.objects.filter(user__pk=self.kwargs['pk']).first()

        if 'change_profile_pic' in request.POST:
            profile_pic_form = ChangeProfilePicForm(request.POST, request.FILES)
            if profile_pic_form.is_valid():
                profile_pic_form.save(customer=customer)
            else:
                context['change_profile_pic_form'] = profile_pic_form
        elif 'change_password' in request.POST:
            password_form = ChangePasswordForm(request.POST)
            if password_form.is_valid():
                password_form.save(user=customer.user)
            else:
                context['change_password_form'] = password_form
        return render(request, self.template_name, self.get_context_data(**context))

biheybazar/customers/templates/customers/base.html
{# customers base.html extends from users(app) base.html #}
{% extends 'users/base.html' %}


{% block content %}
    {% block customercontent %}     
        
    {% endblock customercontent %}
{% endblock content %}
    

    

biheybazar/customers/templates/customers/customers_profile.html
{% extends 'customers/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block customercontent %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% if user.is_customer and customer.user.pk == user.pk %}
<!-- NEW CODE -->
<div class="user-profile-container">
    <div class="user-profile-info">
        <div class="container">
            <div class="user-profile-image">
                <img src="{{ customer.profile_pic.url }}" alt="">
            </div>
            <div class="user-profile-details">
                <h3 class="user-name">{{customer.user.first_name}} {{customer.user.last_name}}</h3>
                <p class="user-email">{{customer.user.email}}</p>
            </div>
            <div class="user-image-change">

                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#staticBackdrop">Change
                    Picture</button>
                <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
                    aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Change Profile Pic</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" action="{% url 'customers:profile' pk=customer.pk %}"
                                    enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% bootstrap_form change_profile_pic_form %}
                                    <input type="submit" class="btn btn-primary" value="Change"
                                        name="change_profile_pic">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- !change password not working -->
    <div class="user-password-change">
        <form method="POST" class="change_password_form" action="{% url 'customers:profile' pk=customer.pk %}">
            {% csrf_token %}
            <h2>Update Password</h2>
            <input type="password" name="old_password" placeholder="Current Password">
            <input type="password" name="new_password" placeholder="New Password">
            <input type="password" name="confirm_password" placeholder="Confirm Password">
            <input type="submit" name="change_password" value="Confirm">
        </form>
    </div>
    <div class="container">
        <center>
            <div style="margin-top:20px;">
                <a class="btn btn-danger" href="{% url 'customers:questions' %}">Change Recommendations</a>
            </div>
        </center>

    </div>
</div>
<!-- NEW CODE -->
<!-- <div>
    <div class="col-lg-2">
        <img class="customerPic" height="300px" width="300px" src="{{ customer.profile_pic.url }}">
    </div>
    <label class="h1"><strong>{{customer.user.first_name}} {{customer.user.last_name}}</strong></label><br>
    <p>{{customer.user.email}}</p>
    <button class="btn btn-warning" data-toggle="modal" data-target="#staticBackdrop">Change Profile Pic</button>
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Change Profile Pic</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="{% url 'customers:profile' pk=customer.pk %}"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form change_profile_pic_form %}
                        <input type="submit" class="btn btn-primary" value="Change" name="change_profile_pic">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<button class="btn btn-danger" id="password-button-show">Change Password</button>
<button type="button" class="btn btn-primary" id="password-button-hide">Close</button>
<form method="POST" id="password-form" action="{% url 'customers:profile' pk=customer.pk %}">
    {% csrf_token %}
    {% bootstrap_form change_password_form %}
    <input type="submit" class="btn btn-primary" name="change_password" value="Change Password">
</form>

</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {

        $("#password-form").hide();
        $("#password-button-show").show();
        $("#password-button-hide").hide();

        $("#password-button-show").click(function () {
            $("#password-form").show();
            $("#password-button-hide").show();
            $("#password-button-show").hide();
        });

        $("#password-button-hide").click(function () {
            $("#password-form").hide();
            $("#password-button-show").show();
            $("#password-button-hide").hide();
        });

    });
</script> -->
{% endif %}


{% endblock customercontent %}

biheybazar/customers/templates/customers/questions.html
{# questions.html extends from customers(app) base.html #}
{% extends 'customers/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}


    <!-- content -->
    <div class="position-relative overflow-hidden py-1 px-5 px-md-5 m-0 text-center bg-light">
        <div class="my-3 mx-auto row p-0 justify-content-center">
            <div class="col-lg-10 p-0 m-0 align-content-center shadow"> <!---->
                <div class="card text-center w-100 py-5 h-100 rounded-0 justify-content-center"> <!---->
                    <!-- form below -->
                    <form class="form-signin" method="POST"> <!---->
                        {% csrf_token %}
                        <!-- label -->
                        <div class="container p-4 ">
                            <h1 class="quesHeader mt-2">
                                <strong>A few questions before we continue</strong>
                            </h1>
                            <!-- container for the two input -->
                            <div class="container justify-content-center">
                                <!-- asking Wedding location -->
                                <div class="container row mb-4">
                                    <h2 class="col-8" >Where is the wedding to be held?</h2>
                                    <div class="col-4">
                                        <select name="location" class="form-control">
                                            <option value="" selected disabled>city here</option>
                                            <option value="1">Kathmandu</option>
                                            <option value="2">Pokhara</option>
                                            <option value="3">Chitwan</option>
                                            <option value="4">Janakpur</option>
                                            <option value="5">Dang</option>
                                        </select>
                                        
                                    </div>
                                </div>
                                <!-- asking Wedding type -->
                                <div class="container row mt-4">
                                    <h2 class="col-8">What is the wedding type?</h2>
                                    <div class="col-4">
                                        <select  name="culture" class="form-control" required>
                                            <option value="" selected disabled>culture/tradition here</option>
                                            <option value="1">Brahmin</option>
                                            <option value="2">Newar</option>
                                            <option value="3">Tharu</option>
                                            <option value="4">Terai</option>
                                        </select>
                                      
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- buttons -->
                        <div class="signupContButtonGroup form-group mb-2">
                            <button class="quesContButton btn btn-lg  btn-danger btn-block" type="submit">Continue</button>
                            <a href="{% url 'home' %}" type="button" class="quesSkipButton btn btn-link"> Skip for now >></a>
                        </div>
                    </form>
                </div>
            </div> 
        </div>

         <!-- footer -->
         <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3"></div>
         <footer class="container pt-5">
             <div class="row pb-5">
                 <div class="col-6 col-md">
                     <h5>Features</h5>
                     <ul class="list-unstyled text-small">
                         <li><a class="text-muted" href="#">Cool stuff</a></li>
                         <li><a class="text-muted" href="#">Random feature</a></li>
                         <li><a class="text-muted" href="#">Team feature</a></li>
                         <li><a class="text-muted" href="#">Stuff for developers</a></li>
                         <li><a class="text-muted" href="#">Another one</a></li>
                         <li><a class="text-muted" href="#">Last time</a></li>
                     </ul>
                 </div>
                 <div class="col-6 col-md">
                     <h5>Resources</h5>
                     <ul class="list-unstyled text-small">
                         <li><a class="text-muted" href="#">Resource</a></li>
                         <li><a class="text-muted" href="#">Resource name</a></li>
                         <li><a class="text-muted" href="#">Another resource</a></li>
                         <li><a class="text-muted" href="#">Final resource</a></li>
                     </ul>
                 </div>
                 <div class="col-6 col-md">
                     <h5>Resources</h5>
                     <ul class="list-unstyled text-small">
                         <li><a class="text-muted" href="#">Business</a></li>
                         <li><a class="text-muted" href="#">Education</a></li>
                         <li><a class="text-muted" href="#">Government</a></li>
                         <li><a class="text-muted" href="#">Gaming</a></li>
                     </ul>
                 </div>
                 <div class="col-6 col-md">
                     <h5>About us</h5>
                     <ul class="list-unstyled text-small">
                         <li><a class="text-muted" href="#">Team</a></li>
                         <li><a class="text-muted" href="#">Locations</a></li>
                         <li><a class="text-muted" href="#">Privacy</a></li>
                         <li><a class="text-muted" href="#">Terms</a></li>
                     </ul>
                 </div>
             </div>
             <div class="row">
                 <div class="col-12 col-md">
                     <small class="d-block mt-3 text-muted">BiheyBazar, &copy;2020</small>
                 </div>
             </div>
         </footer>
    

    
{% endblock content %}
    