biheybazar/biheybazar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from . import views
from users import views as user_views

# Routing is defined here
urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)), # To use django debugger
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^vendors/', include('vendors.urls', namespace="vendors")),
    url(r'^checklist/', include('checklist.urls', namespace="checklist")),
    # path('verification/', include('verify_email.urls')),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     user_views.activate, name='activate'),
    path('activate/<uidb64>/<token>', user_views.activate, name="activate")
] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT) # To include media urls

biheybazar/checklist/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import re_path, path
from users import views as user_views

app_name = "checklist"

urlpatterns = [
    url(r'^$', user_views.checklist_url, name="all"),
    url(r'^create/$', views.CreateChecklist.as_view(), name="checklist_create"),
    re_path(r'^(?P<pk>[-\w]+)/$', views.ChecklistDetail.as_view(), name="checklist_detail"),
    url(r'^delete/note/(?P<pk>[-\w]+)/$', views.DeleteNote.as_view(), name="note_delete"),
    url(r'^delete/category/(?P<pk>[-\w]+)/$', views.DeleteChecklistCategory.as_view(), name="checklistcategory_delete"),
    url(r'^remove/vendor/(?P<pk>[-\w]+)/$', views.RemoveChecklistVendor.as_view(), name="vendor_remove"),
    url(r'^delete/checklist/(?P<pk>[-\w]+)/$', views.DeleteChecklist.as_view(), name="checklist_delete"),
    url(r'^remove/collaborator/(?P<pk>[-\w]+)/$', views.removeCollaborator, name='collaborator_remove'),
]

biheybazar/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'check/',views.userCheckView,name='check'),
    url(r'^signup/customer/$', views.customerSignUpView, name="signup_customer"),
    url(r'^signup/vendor/$', views.vendorSignUpView, name="signup_vendor"),
]

biheybazar/vendors/urls.py
from django.conf.urls import url
from . import views
from reviews import views as re_view

app_name = "vendors"
urlpatterns = [
    url(r'^new/tag/$', views.CreateTag.as_view(), name="create_tag"),
    # url(r'^add/tag/$', views.AddTag.as_view(), name="add_tag"),
    # url(r'^remove/tag/$', views.RemoveTag.as_view(), name="remove_tag"),
    url(r'^new/category/$', views.CreateCategory.as_view(), name="create_category"),
    url(r'^profile/(?P<slug>[-\w]+)/$', views.VendorProfile.as_view(), name='profile'),
    url(r'^delete/image/(?P<pk>[-\w]+)/$', views.DeleteVendorImage.as_view(), name="image_delete"),
    url(r'^delete/pricing/(?P<pk>[-\w]+)/$', views.DeleteVendorPricing.as_view(), name="pricing_delete"),
    url(r'list/', views.VendorListView.as_view(), name="vendor_list"),
    url(r'venues/',views.VenueListView.as_view(),name='venues'),
    url(r'^category/(?P<pk>[-\w]+)/$',views.CategoryDetailView.as_view(),name='vendorCategory'),
    url(r'^recommendations/$', views.RecommendationListView.as_view(), name="recommendation_list"),
]

biheybazar/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# Creates an AbstractUser called User for authentication 
class User(AbstractUser):
    # Boolean Fields for determining user types
    is_customer = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)

    # String representation of the User model
    def __str__(self):
        return self.username

biheybazar/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.contrib.auth import get_user_model
from django.db.transaction import commit
from django.forms import fields
from ckeditor.fields import RichTextField
from .models import User
from customers.models import Customer
from vendors.models import Vendor


# Form for registering user instance in the database for customer signup
class UserCustomerForm(UserCreationForm):
    user = User.objects.all()
    var1=[]
    var2=[]
    # print(user)
    for i in user:
        # print(i)
        var1.append(i.email)
    print(var1)
    # for i,j in enumerate(var1):
    #     var2.append(j)

    # print(var2)
    
    class Meta:
        model = User
        
        
        # for i in user:
        #     var1.append()

        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
    

    # def clean_email(self,*args,**kwags):
    #     email= self.cleaned_data.get('email')
    #     print(email in self.var1)
    #     if email in self.var1:
    #         raise forms.ValidationError("Invalid Email")
    #     else:
    #         return email
            

            
    # @transaction.atomic() # makes the transaction atomic. i.e. all or none
    # def save(self, commit):
    #     user = super().save(commit=False)
    #     user.is_customer = True # determines that the user will registered as customer
    #     user.save(commit=commit)
    #     return user.pk


# Form for registering customer instance in the database for customer signup
class CustomerSignUpForm(forms.ModelForm):
    class Meta:
        exclude = ('user', 'location', 'culture')
        model = Customer

    @transaction.atomic()
    def save(self, user):
        customer = Customer.objects.create(
            user=user, # foreign key -> user object
            profile_pic=self.cleaned_data['profile_pic'])
        return customer

# Form for registering user instance in the database for vendor signup
class UserVendorForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        # widgets={
        #     'about':forms.Textarea(attrs={ 'class':"editable medium-editor-textarea"})
        #     }
    
    # @transaction.atomic()
    # def save(self):
    #     user = super().save(commit=False)
    #     user.is_vendor = True # determines that the user will registered as vendor
    #     user.save()
    #     return user.pk


# Form for registering vendor instance in the database for vendor signup
class VendorSignUpForm(forms.ModelForm):
    user = UserVendorForm()
    class Meta:
        exclude=('user', 'about', 'slug', 'address', 'contact', 'review_int', 'category')
        model = Vendor


        widgets={
            'about':forms.Textarea(attrs={ 'class':"about-text"})
        }



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['vendor_name'].label = 'Vendor Name'
        self.fields['cover_image'].label = 'Cover Image'
        # self.fields['category'].label = 'Categories'
        # self.fields['about'].label=''

    @transaction.atomic()
    def save(self, user, category):
        vendor = Vendor.objects.create(
            review_int=0,
            user=user, # foreign key -> user object
            vendor_name=self.cleaned_data['vendor_name'],
            logo=self.cleaned_data['logo'],
            cover_image=self.cleaned_data['cover_image'],
            # about=self.cleaned_data['about'],
            category=category,
            slug=user.username)
        return vendor

biheybazar/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.db.transaction import commit
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import login
from django.urls.base import reverse_lazy
from django.views.generic import (CreateView, ListView)
from verify_email.email_handler import send_verification_email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage


from .forms import CustomerSignUpForm, VendorSignUpForm, UserVendorForm, UserCustomerForm
from .models import User
from customers.models import Customer
from checklist.models import Checklist

from .tokens import account_activation_token
from vendors.models import Vendor
from vendors.models import Category


from customers.models import Customer

# Create your views here.

# View for signing up the customer
def customerSignUpView(request):
    if request.method == 'POST':

        # Two form needs to be created for signup view
        user_form = UserCustomerForm(request.POST)
        customer_form = CustomerSignUpForm(request.POST, request.FILES)
        errors=str(user_form.errors)
        print(errors)
        if len(errors)>0:
            error=user_form.errors
        else:
            error=''
        # user_form.username.error_messages={'required':"Invalid"}
        if user_form.is_valid() and customer_form.is_valid():
            # form validation and updating models
            user = user_form.save(commit=False)
            user.is_customer = True
            user.save()
            user_obj = User.objects.get(username=user_form.cleaned_data['username'])
            customer_form.save(user_obj)
            # inactive_user = send_verification_email(request, user_form)
            # print(user_form.cleaned_data['email'])
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate you BiheyBazar account'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.content_subtype = "html"
            email.send()
            return HttpResponseRedirect(reverse_lazy("users:login"))        

        else:
            context = {
                'user_form': user_form,
                'customer_form': customer_form,
                'errors':error
            }

    else:
        context = {
            'user_form': UserCustomerForm(),
            'customer_form': CustomerSignUpForm(),
            'errors':'user_form.errors'
        }
    
    

    return render(request, 'users/customer_signup.html', context)


# View for signing up vendor
def vendorSignUpView(request):
    category = Category.objects.all()
    if request.method == 'POST':
        # Two form needs to be created for signup view
        user_form = UserVendorForm(request.POST)
        vendor_form = VendorSignUpForm(request.POST, request.FILES)
        if user_form.is_valid() and vendor_form.is_valid():
            # form validation and updating models
            user = user_form.save(commit=False)
            user.is_vendor=True
            user.save()
            user_obj = User.objects.get(username=user_form.cleaned_data['username'])
            category = Category.objects.filter(category_name=request.POST['category']).first()
            print(category)
            vendor_form.save(user_obj, category)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your BiheyBazar account'
            message = render_to_string('users/acc_active_email.html', {
                'user':user,
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.content_subtype = "html"
            email.send()
            return HttpResponseRedirect(reverse_lazy("users:login"))        

        else:
            context = {
                'categories': category,
                'user_form': user_form,
                'vendor_form': vendor_form,
            }

    else:
        context = {
            'categories': category,
            'user_form': UserVendorForm(),
            'vendor_form': VendorSignUpForm(),
        }

    return render(request, 'users/vendor_signup.html', context)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        return HttpResponseRedirect(reverse_lazy("users:login"))
    else:
        return HttpResponse('Activation link is invalid')


# function view to check the type of user and redirct them accordingly,
def userCheckView(request):
    user = request.user

    #if user is vendor s/he should be redirected to their respective profile
    if user.is_vendor:
        return redirect('vendors:profile', slug=user)

    #if user is customer redirect them to either questions page or home page    
    elif user.is_customer:
        customer=Customer.objects.get(user=user)
        if customer.location==None or customer.culture==None:
            return HttpResponseRedirect(reverse_lazy("customers:questions"))

        else:
            return HttpResponseRedirect(reverse_lazy("home"))
    else:
        return HttpResponseRedirect(reverse_lazy("home"))


def checklist_url(request):
    author_checklists = Checklist.objects.filter(author__user=request.user)
    shared_checklists = Checklist.objects.filter(collaborators__user=request.user)
    if author_checklists:
        pk = author_checklists.first().pk
        return redirect("checklist:checklist_detail", pk=pk)
    else:
        if shared_checklists:
            pk = shared_checklists.first().pk
            return redirect("checklist:checklist_detail", pk=pk)
        else:
            return redirect("checklist:checklist_create")

biheybazar/users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

biheybazar/users/templates/users/base.html
{% load static %}


<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">


    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">



    <title>

        {% block title %}
        {% endblock title %}

    </title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/`/font-awesome/4.7.0/css/font-awesome.min.css">


    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
        type="text/css" media="screen" charset="utf-8">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- <script src="{% static 'js/master.js' %}"></script> -->


    <!-- jquery here -->
    <!-- <link href="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.structure.min.css' %}" rel="stylesheet">
  <link href="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.theme.min.css' %}" rel="stylesheet"> -->

    <link rel="stylesheet" href="{%static 'css/base.css' %}">
    <link rel="stylesheet" href="{%static 'css/test.css' %}">
    <link rel="stylesheet" href="{%static 'css/login.css' %}">
    <link rel="stylesheet" href="{%static 'css/signup.css' %}">
    <link rel="stylesheet" href="{%static 'css/style.css' %}">

    {% block head %}

    {% endblock %}

</head>

<body>
    <div class="sticky-top" id="header">
        <!-- Navigation Bar -->
        <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color:#9f1829;">
            <a class="navbar-brand brand-name" href="{% url 'home' %}"> <img class="brand-image"
                    src="{% static 'images/Logo.png' %}" alt="">
                Bihey Bazar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link navbar-item" href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <hr class="my-0" style="border-top: 1px solid #f2f2f2;">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-item" href="{% url 'vendors:venues' %}">Venues</a>
                    </li>
                    <li>
                        <hr class="my-0" style="border-top: 1px solid #f2f2f2;">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-item" href="{% url 'vendors:vendor_list' %}">Vendors</a>
                    </li>
                    <li>
                        <hr class="my-0" style="border-top: 1px solid #f2f2f2;">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-item" href="{% url 'vendors:recommendation_list' %}">Recommended</a>
                    </li>
                    <li>
                        <hr class="my-0" style="border-top: 1px solid #f2f2f2;">
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item ">
                        <a class="nav-link navbar-item" href="{% url 'checklist:all' %}">Checklist</a>
                    </li>
                    {% endif %}
                </ul>




                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="btn dropdown-button" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <img class="profile-image" src="
                                {% if user.is_customer %}
                                    {{customer_context.profile_pic.url}}
                                {% else %}
                                    {{vendor_context.logo.url}}
                                {% endif %}
                            "> &nbsp;
                            {{user.username}}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            {% if user.is_customer %}
                                <a class="dropdown-item" href="{% url 'customers:profile' pk=user.customer.pk %}">My Profile</a>
                            {% elif user.is_vendor %}
                                <a class="dropdown-item" href="{% url 'vendors:profile' slug=user.username %}">My Profile</a>
                            {% endif %}
                            <a class="dropdown-item" href="#">Feature</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                        </div>

                    </li>
                </ul>
            </div>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="btn login-button" href="{% url 'users:login' %}" role="button">Login</a>
                </li>
            </ul>
            {% block precontent%}
            {% endblock precontent%}


            {# injection of signup as customer from vendor_signup.html #}
            {% block altercontent%}
            {% endblock altercontent%}

            {# injection of login button from index.html #}
            {% block logincontent %}
            {% endblock logincontent %}

            {% endif %}

        </nav>

    </div>





    {# all the lines of code inside block body-content will be injected here#}
    {% block body_content %}
    {% endblock body_content %}


    {# all the lines of code inside block content will be injected here#}
    {% block content %}
    {% endblock content %}

    <hr>
            <footer class="container pt-1 pb-2">
                <div class="row">
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">BiheyBazar</a>
                    </div>
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">Help</a>
                    </div>
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">FAQ</a>
                    </div>
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">Terms</a>
                    </div>
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">Pricing</a>
                    </div>
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">About Us</a>
                    </div>
                    <div class="col-6 col-md">
                        <a class="list-unstyled text-muted" href="#">Contact</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md">
                        <small class="d-block mt-3 text-muted" style="text-align: center;">
                            &copy;2021 BiheyBazar</small>
                    </div>
                </div>
            </footer>



    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <!-- javascript here -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
    <script src="{% static 'js/custom-jquery.js' %}"></script>

    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->


</body>

</html>

biheybazar/users/templates/users/index.html
{# index.html extends from users base.html #}
{% extends 'users/base.html' %}
{% load static%}
{% load bootstrap4 %}

{# this block contains login button #}




{# block content contains the main content of this page#}
{% block content %}

<style>
  .checked {
    color: orange;
  }
</style>
<div id="slides" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#slides" data-slide-to="0" class="active"></li>
    <li data-target="#slides" data-slide-to="1"></li>
    <li data-target="#slides" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/background.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Make your wedding the way you want</h5>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/background.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Make your wedding the way you want</h5>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/background.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Make your wedding the way you want</h5>
      </div>
    </div>
  </div>
</div>
<!-- Content -->
<div class="container content-container">
  <!-- Small Description -->
  <div class="jumbotron shadow mt-4">
    <p class="lead">Welcome to Bihey Bazar, we connect the customers with various venue owners and categories of
      vendors required for a wedding
      allowing the customers to consider the services in their checklist.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Explore</a>
  </div>
  <!-- Featured Vendors -->
  <!-- Heading -->
  <div class="container-fluid padding">
    <div class="row welcome text-left">
      <div class="col-12">
        <h3>Featured Vendors</h3>
      </div>
    </div>
    <div class="row welcome text-right">
      <div class="col-12">
        <a href="{% url 'vendors:vendor_list' %}" style="text-decoration: none;">Show more ></a>
      </div>
    </div>
  </div>
  <!-- Cards -->
  <div class="container-fluid padding">
    <!-- Row1 -->
    <div class="row">
      {% for vendor in ordered_vendor %}
      <div class="col-sm-3">
        <div class="card mb-4 shadow" style="height: 320px; width: 200px;">
          <img class="card-img-top" src="{{ vendor.logo.url }}" width="200px" height="200px">
          <div class="card-body">
            <h5 class="card-title">{{vendor.vendor_name}}</h5>
            <a href="{% url 'vendors:profile' slug=vendor.user.username %}" class="stretched-link"></a>
            <div class="">
              {% ifequal vendor.review_int 1 %}
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn "></span>
              <span class="fa fa-star my-btn "></span>
              <span class="fa fa-star my-btn "></span>
              <span class="fa fa-star my-btn"></span>
              {% endifequal %}

              {% ifequal vendor.review_int 2 %}
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn "></span>
              <span class="fa fa-star my-btn "></span>
              <span class="fa fa-star my-btn"></span>
              {% endifequal %}

              {% ifequal vendor.review_int 3 %}
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn "></span>
              <span class="fa fa-star my-btn"></span>
              {% endifequal %}

              {% ifequal vendor.review_int 4 %}
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn"></span>
              {% endifequal %}

              {% ifequal vendor.review_int 5 %}
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              <span class="fa fa-star my-btn checked"></span>
              {% endifequal %}
            </div>

          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- Vendor Categories -->
  <!-- Categories -->
  <div class="container-fluid padding">
    <div class="row welcome text-left">
      <div class="col-12">
        <h3>Vendor Categories</h3>
      </div>
    </div>
    <div class="row welcome text-right">
      <div class="col-12">
        <a href="{% url 'vendors:vendor_list' %}" style="text-decoration: none;">Show more ></a>
      </div>
    </div>
  </div>
  <!-- Cards -->
  <div class="container-fluid padding">

    <div class="row">
      {% for category in categories %}
      <div class="col-sm-3">
        <div class="card mb-4 shadow">
          <img class="card-img-top" src="{% static 'images/vase.jpg'  %}">
          <div class="card-body">
            <h5 class="card-title">{{category.category_name}}</h5>
            <a href="{% url 'vendors:vendorCategory' pk=category.pk %}" class="stretched-link"></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

  </div>
</div>
</div>
</main>


{% endblock content %}